/**
 * Curated list of major cities per country, used as suggestion chips in the
 * Google Maps scraper. Order = roughly population / business density (top
 * comes first because we cap displayed chips at MAX_CITY_SUGGESTIONS).
 *
 * Keep this list short and high-signal. Niche cities can still be typed by
 * hand — the input remains free-text.
 */

export const MAX_CITY_SUGGESTIONS = 12;

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  México: [
    "CDMX",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Toluca",
    "Querétaro",
    "Ciudad Juárez",
    "Mérida",
    "Cancún",
    "Aguascalientes",
    "Saltillo",
    "Hermosillo",
    "San Luis Potosí",
    "Culiacán",
    "Chihuahua",
    "Veracruz",
    "Morelia",
    "Cuernavaca",
  ],
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Manizales",
    "Villavicencio",
    "Pasto",
    "Neiva",
    "Armenia",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "Tucumán",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Neuquén",
    "Bahía Blanca",
    "Corrientes",
    "Posadas",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Iquique",
    "Talca",
    "Arica",
    "Chillán",
    "Puerto Montt",
    "Valdivia",
    "Punta Arenas",
  ],
  Perú: [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Piura",
    "Iquitos",
    "Cusco",
    "Huancayo",
    "Tacna",
    "Pucallpa",
    "Ica",
    "Chimbote",
    "Cajamarca",
    "Ayacucho",
  ],
  España: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Granada",
    "A Coruña",
    "Pamplona",
    "Santander",
  ],
  "Estados Unidos": [
    "Los Angeles",
    "New York",
    "Houston",
    "Miami",
    "Chicago",
    "Dallas",
    "San Antonio",
    "Phoenix",
    "San Diego",
    "Austin",
    "Las Vegas",
    "El Paso",
    "Denver",
    "San Francisco",
    "Atlanta",
    "Orlando",
    "Tampa",
    "Seattle",
  ],
  Ecuador: [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Manta",
    "Portoviejo",
    "Loja",
    "Ambato",
    "Riobamba",
    "Esmeraldas",
    "Ibarra",
  ],
  Guatemala: [
    "Ciudad de Guatemala",
    "Mixco",
    "Villa Nueva",
    "Quetzaltenango",
    "Escuintla",
    "Cobán",
    "Huehuetenango",
    "Antigua Guatemala",
    "Chimaltenango",
    "Mazatenango",
    "Petapa",
    "Amatitlán",
  ],
};
